### ISSUE TITLE
There are no commands defined in the "snooze" namespace

### ISSUE THREAD

**Issue by arun07as** [thomasjohnkane/snooze#59]
Hi
I'm getting the following error in my `schedule:run` cron job

```
[2020-08-06 13:56:02] local.ERROR: There are no commands defined in the "snooze" namespace. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"snooze\" namespace. at /home2/foldernamechanged/public_html/testing/vendor/symfony/console/Application.php:597)
[stacktrace]
#0 /home2/foldernamechanged/public_html/testing/vendor/symfony/console/Application.php(650): Symfony\\Component\\Console\\Application->findNamespace('snooze')
#1 /home2/foldernamechanged/public_html/testing/vendor/symfony/console/Application.php(235): Symfony\\Component\\Console\\Application->find('snooze:send')
#2 /home2/foldernamechanged/public_html/testing/vendor/symfony/console/Application.php(147): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#3 /home2/foldernamechanged/public_html/testing/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#4 /home2/foldernamechanged/public_html/testing/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(133): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#5 /home2/foldernamechanged/public_html/testing/artisan(36): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#6 {main}
"} 
```

`sendFrequency` is set to `everyMinute` so I'm getting this error every minute now.

When I manually run `schedule:run` or `snooze:send` in console it works fine. The issue seems to occur only in the cron job. 
Running `php artisan` shows 

```
 snooze
  snooze:prune                  Prune scheduled notifications that have been sent or cancelled
  snooze:send                   Send scheduled notifications that are ready to be sent.
```

Searching the web, most answers were to run `config:clear` , `cache:clear`, `composer dump-autoload`, but no luck doing that.

Any ideas on what could be wrong?

### System Details

**php:** 7.2.32
**laravel:** 5.8.38
**snooze:** 1.0.3
**os:** CentOS Linux release 7.8.2003 (Core)

**Comment by atymic** [comment]
I think this might be your laravel version 🤔

**Comment by atymic** [comment]
Still having this issue?

**Comment by arun07as** [comment]
I didn't find any solution to fix the issue. In the end, I set up the command to run once a year by setting the send frequency to yearly in the config file so that it won't run that much. Then I just added an entry in `kernel.php` manually to run the `snooze:send` command every minute and it's working fine for now.

**Comment by Zzombiee2361** [comment]
I'm having the same issue. How am I supposed to debug this?

### System Details
php: 7.4.19
laravel: 8.45.1
snooze: master
os: CentOS Linux release 7.9.2009 (Core)

**Comment by Zzombiee2361** [comment]
I found the solution. Turns out the php I ran on the cron job is different from php that I ran from ssh. Basically it's not php cli, that causes `$this->app->runningInConsole()` to return `false`, so that's why the command is never registered.

The fix is easy, I just use the php's absolute path from the ssh, like so:
```
* * * * * cd /path/to/project && /usr/local/bin/php artisan schedule:run >> /dev/null 2>&1
```

**Comment by atymic** [comment]
Closing due to inactivity.
