### ISSUE TITLE
Type error: Argument 1 passed to Thomasjohnkane\Snooze\ScheduledNotification::create() must be an instance of Thomasjohnkane\Snooze\object

### ISSUE THREAD

**Issue by olezhkafp** [thomasjohnkane/snooze#66]
Hi. We used this good package at our stage server, at local version it is also works fine, but today we are added it to the production server (master branch is equal to stage branch) and got an error:

```
Type error: Argument 1 passed to Thomasjohnkane\Snooze\ScheduledNotification::create() must be an instance of Thomasjohnkane\Snooze\object, 
instance of App\Models\VideoCall given, called in [...]/public/vendor/thomasjohnkane/snooze/src/Traits/SnoozeNotifiable.php on line 23
{"userId":40,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed
to Thomasjohnkane\\Snooze\\ScheduledNotification::create() must be an instance of Thomasjohnkane\\Snooze\\object,
instance of App\\Models\\VideoCall given, called in [...]/public/vendor/thomasjohnkane/snooze/src/Traits/SnoozeNotifiable.php
on line 23 at [...]/vendor/thomasjohnkane/snooze/src/ScheduledNotification.php:37)
[stacktrace]

#0 [...]/public/vendor/thomasjohnkane/snooze/src/Traits/SnoozeNotifiable.php(23):
Thomasjohnkane\\Snooze\\ScheduledNotification::create(Object(App\\Models\\VideoCall), Object(App\\Notifications\\VideoCallsNotice), Object(Carbon\\Carbon))

#1 [...]/public/app/Observers/VideoCallObserver.php(21):
App\\Models\\VideoCall->notifyAt(Object(App\\Notifications\\VideoCallsNotice), Object(Carbon\\Carbon))

#2 [internal function]: App\\Observers\\VideoCallObserver->created(Object(App\\Models\\VideoCall))
```

Our model VideoCall uses Notifiable and SnoozeNotifiable traits.

And we are calling it:

`$call->notifyAt(new VideoCallsNotice(), $startDate->subMinutes(30));`

Laravel 5.6
PHP 7.2.33

Maybe some PHP extension needs to be enabled, or something else?

**Comment by olezhkafp** [comment]
The problem was in PHP version, as server used serverpilot there is was enabled 7.1
